-- 0009: directory expansion (additive; D12). Adds 212 well-known real employers (name, slug and sector only: no headquarters, headcount or founding year) with INSERT OR IGNORE, so an employer whose id or slug already exists is skipped and no existing row changes. Adds company_aliases (curated names used to match questions to listed employers, on the device and in the inference prefilter) with 351 rows, including other well-known names of four employers already listed (Google: Alphabet; Meta: Facebook; Amazon: AWS; Microsoft: MSFT). No verification domains or issuer keys are added: these employers show that verification is not set up yet until domains are configured. No foreign key on company_aliases, because db/seed.sql (local only) deletes companies.
--
-- company_aliases.alias: case-insensitive aliases are stored normalized (lowercase words separated by single spaces);
-- cased aliases (cased=1) are stored as written ("Target", "AT&T") and name the employer only when written in exactly
-- that case or as the whole question, because they are common words or single-letter acronyms.

CREATE TABLE IF NOT EXISTS company_aliases (
  company_id TEXT NOT NULL,
  alias TEXT NOT NULL,
  cased INTEGER NOT NULL DEFAULT 0 CHECK (cased IN (0, 1)),
  PRIMARY KEY (company_id, alias)
);
CREATE INDEX IF NOT EXISTS company_aliases_alias ON company_aliases(alias);

INSERT OR IGNORE INTO companies (id, slug, name, kind, sector, coverage_note) VALUES
 ('co-salesforce','salesforce','Salesforce','real','Software','No verified evidence published yet.'),
 ('co-oracle','oracle','Oracle','real','Software','No verified evidence published yet.'),
 ('co-adobe','adobe','Adobe','real','Software','No verified evidence published yet.'),
 ('co-sap','sap','SAP','real','Software','No verified evidence published yet.'),
 ('co-servicenow','servicenow','ServiceNow','real','Software','No verified evidence published yet.'),
 ('co-workday','workday','Workday','real','Software','No verified evidence published yet.'),
 ('co-snowflake','snowflake','Snowflake','real','Software','No verified evidence published yet.'),
 ('co-databricks','databricks','Databricks','real','Software','No verified evidence published yet.'),
 ('co-palantir','palantir','Palantir Technologies','real','Software','No verified evidence published yet.'),
 ('co-atlassian','atlassian','Atlassian','real','Software','No verified evidence published yet.'),
 ('co-intuit','intuit','Intuit','real','Software','No verified evidence published yet.'),
 ('co-autodesk','autodesk','Autodesk','real','Software','No verified evidence published yet.'),
 ('co-shopify','shopify','Shopify','real','Software','No verified evidence published yet.'),
 ('co-datadog','datadog','Datadog','real','Software','No verified evidence published yet.'),
 ('co-zoom','zoom','Zoom Communications','real','Software','No verified evidence published yet.'),
 ('co-figma','figma','Figma','real','Software','No verified evidence published yet.'),
 ('co-canva','canva','Canva','real','Software','No verified evidence published yet.'),
 ('co-notion','notion','Notion Labs','real','Software','No verified evidence published yet.'),
 ('co-ibm','ibm','IBM','real','Software','No verified evidence published yet.'),
 ('co-epic-systems','epic-systems','Epic Systems','real','Software','No verified evidence published yet.'),
 ('co-uber','uber','Uber','real','Internet','No verified evidence published yet.'),
 ('co-lyft','lyft','Lyft','real','Internet','No verified evidence published yet.'),
 ('co-airbnb','airbnb','Airbnb','real','Internet','No verified evidence published yet.'),
 ('co-doordash','doordash','DoorDash','real','Internet','No verified evidence published yet.'),
 ('co-instacart','instacart','Instacart','real','Internet','No verified evidence published yet.'),
 ('co-pinterest','pinterest','Pinterest','real','Internet','No verified evidence published yet.'),
 ('co-reddit','reddit','Reddit','real','Internet','No verified evidence published yet.'),
 ('co-snap','snap','Snap','real','Internet','No verified evidence published yet.'),
 ('co-bytedance','bytedance','ByteDance','real','Internet','No verified evidence published yet.'),
 ('co-ebay','ebay','eBay','real','Internet','No verified evidence published yet.'),
 ('co-zillow','zillow','Zillow','real','Internet','No verified evidence published yet.'),
 ('co-expedia','expedia','Expedia Group','real','Internet','No verified evidence published yet.'),
 ('co-duolingo','duolingo','Duolingo','real','Internet','No verified evidence published yet.'),
 ('co-visa','visa','Visa','real','Payments','No verified evidence published yet.'),
 ('co-mastercard','mastercard','Mastercard','real','Payments','No verified evidence published yet.'),
 ('co-paypal','paypal','PayPal','real','Payments','No verified evidence published yet.'),
 ('co-block','block','Block','real','Payments','No verified evidence published yet.'),
 ('co-adyen','adyen','Adyen','real','Payments','No verified evidence published yet.'),
 ('co-affirm','affirm','Affirm','real','Payments','No verified evidence published yet.'),
 ('co-klarna','klarna','Klarna','real','Payments','No verified evidence published yet.'),
 ('co-plaid','plaid','Plaid','real','Payments','No verified evidence published yet.'),
 ('co-brex','brex','Brex','real','Payments','No verified evidence published yet.'),
 ('co-ramp','ramp','Ramp','real','Payments','No verified evidence published yet.'),
 ('co-american-express','american-express','American Express','real','Financial services','No verified evidence published yet.'),
 ('co-charles-schwab','charles-schwab','Charles Schwab','real','Financial services','No verified evidence published yet.'),
 ('co-robinhood','robinhood','Robinhood','real','Financial services','No verified evidence published yet.'),
 ('co-coinbase','coinbase','Coinbase','real','Financial services','No verified evidence published yet.'),
 ('co-sofi','sofi','SoFi','real','Financial services','No verified evidence published yet.'),
 ('co-chime','chime','Chime','real','Financial services','No verified evidence published yet.'),
 ('co-jane-street','jane-street','Jane Street','real','Financial services','No verified evidence published yet.'),
 ('co-jpmorgan-chase','jpmorgan-chase','JPMorgan Chase','real','Banking','No verified evidence published yet.'),
 ('co-bank-of-america','bank-of-america','Bank of America','real','Banking','No verified evidence published yet.'),
 ('co-wells-fargo','wells-fargo','Wells Fargo','real','Banking','No verified evidence published yet.'),
 ('co-citigroup','citigroup','Citigroup','real','Banking','No verified evidence published yet.'),
 ('co-goldman-sachs','goldman-sachs','Goldman Sachs','real','Banking','No verified evidence published yet.'),
 ('co-morgan-stanley','morgan-stanley','Morgan Stanley','real','Banking','No verified evidence published yet.'),
 ('co-capital-one','capital-one','Capital One','real','Banking','No verified evidence published yet.'),
 ('co-us-bank','us-bank','U.S. Bank','real','Banking','No verified evidence published yet.'),
 ('co-fidelity','fidelity','Fidelity Investments','real','Asset management','No verified evidence published yet.'),
 ('co-vanguard','vanguard','Vanguard','real','Asset management','No verified evidence published yet.'),
 ('co-blackrock','blackrock','BlackRock','real','Asset management','No verified evidence published yet.'),
 ('co-state-street','state-street','State Street','real','Asset management','No verified evidence published yet.'),
 ('co-citadel','citadel','Citadel','real','Asset management','No verified evidence published yet.'),
 ('co-two-sigma','two-sigma','Two Sigma','real','Asset management','No verified evidence published yet.'),
 ('co-bridgewater','bridgewater','Bridgewater Associates','real','Asset management','No verified evidence published yet.'),
 ('co-blackstone','blackstone','Blackstone','real','Asset management','No verified evidence published yet.'),
 ('co-state-farm','state-farm','State Farm','real','Insurance','No verified evidence published yet.'),
 ('co-progressive','progressive','Progressive','real','Insurance','No verified evidence published yet.'),
 ('co-allstate','allstate','Allstate','real','Insurance','No verified evidence published yet.'),
 ('co-liberty-mutual','liberty-mutual','Liberty Mutual','real','Insurance','No verified evidence published yet.'),
 ('co-geico','geico','GEICO','real','Insurance','No verified evidence published yet.'),
 ('co-metlife','metlife','MetLife','real','Insurance','No verified evidence published yet.'),
 ('co-usaa','usaa','USAA','real','Insurance','No verified evidence published yet.'),
 ('co-unitedhealth-group','unitedhealth-group','UnitedHealth Group','real','Healthcare','No verified evidence published yet.'),
 ('co-cvs-health','cvs-health','CVS Health','real','Healthcare','No verified evidence published yet.'),
 ('co-elevance-health','elevance-health','Elevance Health','real','Healthcare','No verified evidence published yet.'),
 ('co-cigna','cigna','The Cigna Group','real','Healthcare','No verified evidence published yet.'),
 ('co-humana','humana','Humana','real','Healthcare','No verified evidence published yet.'),
 ('co-kaiser-permanente','kaiser-permanente','Kaiser Permanente','real','Healthcare','No verified evidence published yet.'),
 ('co-mayo-clinic','mayo-clinic','Mayo Clinic','real','Healthcare','No verified evidence published yet.'),
 ('co-cleveland-clinic','cleveland-clinic','Cleveland Clinic','real','Healthcare','No verified evidence published yet.'),
 ('co-pfizer','pfizer','Pfizer','real','Pharmaceuticals','No verified evidence published yet.'),
 ('co-johnson-and-johnson','johnson-and-johnson','Johnson & Johnson','real','Pharmaceuticals','No verified evidence published yet.'),
 ('co-merck','merck','Merck & Co.','real','Pharmaceuticals','No verified evidence published yet.'),
 ('co-abbvie','abbvie','AbbVie','real','Pharmaceuticals','No verified evidence published yet.'),
 ('co-eli-lilly','eli-lilly','Eli Lilly','real','Pharmaceuticals','No verified evidence published yet.'),
 ('co-bristol-myers-squibb','bristol-myers-squibb','Bristol Myers Squibb','real','Pharmaceuticals','No verified evidence published yet.'),
 ('co-amgen','amgen','Amgen','real','Pharmaceuticals','No verified evidence published yet.'),
 ('co-gilead','gilead','Gilead Sciences','real','Pharmaceuticals','No verified evidence published yet.'),
 ('co-moderna','moderna','Moderna','real','Pharmaceuticals','No verified evidence published yet.'),
 ('co-genentech','genentech','Genentech','real','Pharmaceuticals','No verified evidence published yet.'),
 ('co-medtronic','medtronic','Medtronic','real','Medical devices','No verified evidence published yet.'),
 ('co-abbott','abbott','Abbott','real','Medical devices','No verified evidence published yet.'),
 ('co-stryker','stryker','Stryker','real','Medical devices','No verified evidence published yet.'),
 ('co-boston-scientific','boston-scientific','Boston Scientific','real','Medical devices','No verified evidence published yet.'),
 ('co-intuitive-surgical','intuitive-surgical','Intuitive Surgical','real','Medical devices','No verified evidence published yet.'),
 ('co-ge-healthcare','ge-healthcare','GE HealthCare','real','Medical devices','No verified evidence published yet.'),
 ('co-thermo-fisher','thermo-fisher','Thermo Fisher Scientific','real','Life sciences','No verified evidence published yet.'),
 ('co-illumina','illumina','Illumina','real','Life sciences','No verified evidence published yet.'),
 ('co-mckinsey','mckinsey','McKinsey & Company','real','Consulting','No verified evidence published yet.'),
 ('co-bcg','bcg','Boston Consulting Group','real','Consulting','No verified evidence published yet.'),
 ('co-bain','bain','Bain & Company','real','Consulting','No verified evidence published yet.'),
 ('co-deloitte','deloitte','Deloitte','real','Consulting','No verified evidence published yet.'),
 ('co-pwc','pwc','PwC','real','Consulting','No verified evidence published yet.'),
 ('co-ey','ey','EY','real','Consulting','No verified evidence published yet.'),
 ('co-kpmg','kpmg','KPMG','real','Consulting','No verified evidence published yet.'),
 ('co-accenture','accenture','Accenture','real','Consulting','No verified evidence published yet.'),
 ('co-booz-allen','booz-allen','Booz Allen Hamilton','real','Consulting','No verified evidence published yet.'),
 ('co-cognizant','cognizant','Cognizant','real','IT services','No verified evidence published yet.'),
 ('co-infosys','infosys','Infosys','real','IT services','No verified evidence published yet.'),
 ('co-tcs','tcs','Tata Consultancy Services','real','IT services','No verified evidence published yet.'),
 ('co-capgemini','capgemini','Capgemini','real','IT services','No verified evidence published yet.'),
 ('co-walmart','walmart','Walmart','real','Retail','No verified evidence published yet.'),
 ('co-target','target','Target','real','Retail','No verified evidence published yet.'),
 ('co-costco','costco','Costco','real','Retail','No verified evidence published yet.'),
 ('co-home-depot','home-depot','The Home Depot','real','Retail','No verified evidence published yet.'),
 ('co-lowes','lowes','Lowe''s','real','Retail','No verified evidence published yet.'),
 ('co-best-buy','best-buy','Best Buy','real','Retail','No verified evidence published yet.'),
 ('co-kroger','kroger','Kroger','real','Retail','No verified evidence published yet.'),
 ('co-walgreens','walgreens','Walgreens','real','Retail','No verified evidence published yet.'),
 ('co-macys','macys','Macy''s','real','Retail','No verified evidence published yet.'),
 ('co-tjx','tjx','TJX Companies','real','Retail','No verified evidence published yet.'),
 ('co-gap','gap','Gap Inc.','real','Retail','No verified evidence published yet.'),
 ('co-ikea','ikea','IKEA','real','Retail','No verified evidence published yet.'),
 ('co-trader-joes','trader-joes','Trader Joe''s','real','Retail','No verified evidence published yet.'),
 ('co-whole-foods','whole-foods','Whole Foods Market','real','Retail','No verified evidence published yet.'),
 ('co-heb','heb','H-E-B','real','Retail','No verified evidence published yet.'),
 ('co-mcdonalds','mcdonalds','McDonald''s','real','Restaurants','No verified evidence published yet.'),
 ('co-starbucks','starbucks','Starbucks','real','Restaurants','No verified evidence published yet.'),
 ('co-chipotle','chipotle','Chipotle Mexican Grill','real','Restaurants','No verified evidence published yet.'),
 ('co-chick-fil-a','chick-fil-a','Chick-fil-A','real','Restaurants','No verified evidence published yet.'),
 ('co-procter-and-gamble','procter-and-gamble','Procter & Gamble','real','Consumer goods','No verified evidence published yet.'),
 ('co-pepsico','pepsico','PepsiCo','real','Consumer goods','No verified evidence published yet.'),
 ('co-coca-cola','coca-cola','The Coca-Cola Company','real','Consumer goods','No verified evidence published yet.'),
 ('co-unilever','unilever','Unilever','real','Consumer goods','No verified evidence published yet.'),
 ('co-nestle','nestle','Nestlé','real','Consumer goods','No verified evidence published yet.'),
 ('co-nike','nike','Nike','real','Consumer goods','No verified evidence published yet.'),
 ('co-tesla','tesla','Tesla','real','Automotive','No verified evidence published yet.'),
 ('co-ford','ford','Ford Motor Company','real','Automotive','No verified evidence published yet.'),
 ('co-general-motors','general-motors','General Motors','real','Automotive','No verified evidence published yet.'),
 ('co-toyota','toyota','Toyota','real','Automotive','No verified evidence published yet.'),
 ('co-honda','honda','Honda','real','Automotive','No verified evidence published yet.'),
 ('co-rivian','rivian','Rivian','real','Automotive','No verified evidence published yet.'),
 ('co-waymo','waymo','Waymo','real','Automotive','No verified evidence published yet.'),
 ('co-boeing','boeing','Boeing','real','Aerospace and defense','No verified evidence published yet.'),
 ('co-lockheed-martin','lockheed-martin','Lockheed Martin','real','Aerospace and defense','No verified evidence published yet.'),
 ('co-northrop-grumman','northrop-grumman','Northrop Grumman','real','Aerospace and defense','No verified evidence published yet.'),
 ('co-rtx','rtx','RTX','real','Aerospace and defense','No verified evidence published yet.'),
 ('co-spacex','spacex','SpaceX','real','Aerospace and defense','No verified evidence published yet.'),
 ('co-anduril','anduril','Anduril Industries','real','Aerospace and defense','No verified evidence published yet.'),
 ('co-ge-aerospace','ge-aerospace','GE Aerospace','real','Aerospace and defense','No verified evidence published yet.'),
 ('co-honeywell','honeywell','Honeywell','real','Industrial','No verified evidence published yet.'),
 ('co-3m','3m','3M','real','Industrial','No verified evidence published yet.'),
 ('co-caterpillar','caterpillar','Caterpillar','real','Industrial','No verified evidence published yet.'),
 ('co-deere','deere','Deere & Company','real','Industrial','No verified evidence published yet.'),
 ('co-siemens','siemens','Siemens','real','Industrial','No verified evidence published yet.'),
 ('co-att','att','AT&T','real','Telecommunications','No verified evidence published yet.'),
 ('co-verizon','verizon','Verizon','real','Telecommunications','No verified evidence published yet.'),
 ('co-t-mobile','t-mobile','T-Mobile','real','Telecommunications','No verified evidence published yet.'),
 ('co-comcast','comcast','Comcast','real','Telecommunications','No verified evidence published yet.'),
 ('co-disney','disney','The Walt Disney Company','real','Media and entertainment','No verified evidence published yet.'),
 ('co-netflix','netflix','Netflix','real','Media and entertainment','No verified evidence published yet.'),
 ('co-warner-bros-discovery','warner-bros-discovery','Warner Bros. Discovery','real','Media and entertainment','No verified evidence published yet.'),
 ('co-spotify','spotify','Spotify','real','Media and entertainment','No verified evidence published yet.'),
 ('co-bloomberg','bloomberg','Bloomberg','real','Media and entertainment','No verified evidence published yet.'),
 ('co-electronic-arts','electronic-arts','Electronic Arts','real','Video games','No verified evidence published yet.'),
 ('co-epic-games','epic-games','Epic Games','real','Video games','No verified evidence published yet.'),
 ('co-roblox','roblox','Roblox','real','Video games','No verified evidence published yet.'),
 ('co-riot-games','riot-games','Riot Games','real','Video games','No verified evidence published yet.'),
 ('co-ups','ups','UPS','real','Logistics','No verified evidence published yet.'),
 ('co-fedex','fedex','FedEx','real','Logistics','No verified evidence published yet.'),
 ('co-dhl','dhl','DHL','real','Logistics','No verified evidence published yet.'),
 ('co-flexport','flexport','Flexport','real','Logistics','No verified evidence published yet.'),
 ('co-delta-air-lines','delta-air-lines','Delta Air Lines','real','Airlines','No verified evidence published yet.'),
 ('co-united-airlines','united-airlines','United Airlines','real','Airlines','No verified evidence published yet.'),
 ('co-american-airlines','american-airlines','American Airlines','real','Airlines','No verified evidence published yet.'),
 ('co-southwest-airlines','southwest-airlines','Southwest Airlines','real','Airlines','No verified evidence published yet.'),
 ('co-jetblue','jetblue','JetBlue','real','Airlines','No verified evidence published yet.'),
 ('co-exxonmobil','exxonmobil','ExxonMobil','real','Energy','No verified evidence published yet.'),
 ('co-chevron','chevron','Chevron','real','Energy','No verified evidence published yet.'),
 ('co-shell','shell','Shell','real','Energy','No verified evidence published yet.'),
 ('co-bp','bp','BP','real','Energy','No verified evidence published yet.'),
 ('co-marriott','marriott','Marriott International','real','Hospitality','No verified evidence published yet.'),
 ('co-hilton','hilton','Hilton','real','Hospitality','No verified evidence published yet.'),
 ('co-hyatt','hyatt','Hyatt','real','Hospitality','No verified evidence published yet.'),
 ('co-scale-ai','scale-ai','Scale AI','real','Artificial intelligence','No verified evidence published yet.'),
 ('co-cohere','cohere','Cohere','real','Artificial intelligence','No verified evidence published yet.'),
 ('co-hugging-face','hugging-face','Hugging Face','real','Artificial intelligence','No verified evidence published yet.'),
 ('co-perplexity','perplexity','Perplexity','real','Artificial intelligence','No verified evidence published yet.'),
 ('co-xai','xai','xAI','real','Artificial intelligence','No verified evidence published yet.'),
 ('co-apple','apple','Apple','real','Consumer electronics','No verified evidence published yet.'),
 ('co-samsung','samsung','Samsung Electronics','real','Consumer electronics','No verified evidence published yet.'),
 ('co-sony','sony','Sony','real','Consumer electronics','No verified evidence published yet.'),
 ('co-dell','dell','Dell Technologies','real','Hardware','No verified evidence published yet.'),
 ('co-hp','hp','HP Inc.','real','Hardware','No verified evidence published yet.'),
 ('co-hpe','hpe','Hewlett Packard Enterprise','real','Hardware','No verified evidence published yet.'),
 ('co-lenovo','lenovo','Lenovo','real','Hardware','No verified evidence published yet.'),
 ('co-cisco','cisco','Cisco','real','Internet infrastructure','No verified evidence published yet.'),
 ('co-arista','arista','Arista Networks','real','Internet infrastructure','No verified evidence published yet.'),
 ('co-intel','intel','Intel','real','Semiconductors','No verified evidence published yet.'),
 ('co-amd','amd','AMD','real','Semiconductors','No verified evidence published yet.'),
 ('co-qualcomm','qualcomm','Qualcomm','real','Semiconductors','No verified evidence published yet.'),
 ('co-broadcom','broadcom','Broadcom','real','Semiconductors','No verified evidence published yet.'),
 ('co-micron','micron','Micron Technology','real','Semiconductors','No verified evidence published yet.'),
 ('co-texas-instruments','texas-instruments','Texas Instruments','real','Semiconductors','No verified evidence published yet.'),
 ('co-arm','arm','Arm','real','Semiconductors','No verified evidence published yet.'),
 ('co-asml','asml','ASML','real','Semiconductors','No verified evidence published yet.'),
 ('co-tsmc','tsmc','TSMC','real','Semiconductors','No verified evidence published yet.'),
 ('co-palo-alto-networks','palo-alto-networks','Palo Alto Networks','real','Cybersecurity','No verified evidence published yet.'),
 ('co-crowdstrike','crowdstrike','CrowdStrike','real','Cybersecurity','No verified evidence published yet.'),
 ('co-fortinet','fortinet','Fortinet','real','Cybersecurity','No verified evidence published yet.'),
 ('co-okta','okta','Okta','real','Cybersecurity','No verified evidence published yet.');

INSERT OR IGNORE INTO company_aliases (company_id, alias, cased) VALUES
 ('co-salesforce','salesforce',0),
 ('co-oracle','oracle',0),
 ('co-adobe','adobe',0),
 ('co-sap','SAP',1),
 ('co-servicenow','servicenow',0),
 ('co-servicenow','service now',0),
 ('co-workday','Workday',1),
 ('co-snowflake','Snowflake',1),
 ('co-databricks','databricks',0),
 ('co-palantir','palantir technologies',0),
 ('co-palantir','palantir',0),
 ('co-atlassian','atlassian',0),
 ('co-intuit','intuit',0),
 ('co-autodesk','autodesk',0),
 ('co-shopify','shopify',0),
 ('co-datadog','datadog',0),
 ('co-zoom','zoom communications',0),
 ('co-zoom','Zoom',1),
 ('co-zoom','zoom video',0),
 ('co-zoom','zoom video communications',0),
 ('co-figma','figma',0),
 ('co-canva','canva',0),
 ('co-notion','notion labs',0),
 ('co-notion','Notion',1),
 ('co-ibm','ibm',0),
 ('co-epic-systems','epic systems',0),
 ('co-uber','uber',0),
 ('co-lyft','lyft',0),
 ('co-airbnb','airbnb',0),
 ('co-doordash','doordash',0),
 ('co-doordash','door dash',0),
 ('co-instacart','instacart',0),
 ('co-pinterest','pinterest',0),
 ('co-reddit','reddit',0),
 ('co-snap','Snap',1),
 ('co-snap','snapchat',0),
 ('co-snap','snap inc',0),
 ('co-bytedance','bytedance',0),
 ('co-bytedance','byte dance',0),
 ('co-ebay','ebay',0),
 ('co-zillow','zillow',0),
 ('co-expedia','expedia group',0),
 ('co-expedia','expedia',0),
 ('co-duolingo','duolingo',0),
 ('co-visa','Visa',1),
 ('co-visa','visa inc',0),
 ('co-mastercard','mastercard',0),
 ('co-mastercard','master card',0),
 ('co-paypal','paypal',0),
 ('co-paypal','pay pal',0),
 ('co-block','Block',1),
 ('co-block','block inc',0),
 ('co-block','Square',1),
 ('co-adyen','adyen',0),
 ('co-affirm','Affirm',1),
 ('co-klarna','klarna',0),
 ('co-plaid','Plaid',1),
 ('co-brex','brex',0),
 ('co-ramp','Ramp',1),
 ('co-american-express','american express',0),
 ('co-american-express','amex',0),
 ('co-charles-schwab','charles schwab',0),
 ('co-charles-schwab','schwab',0),
 ('co-charles-schwab','charlesschwab',0),
 ('co-robinhood','robinhood',0),
 ('co-robinhood','robinhood markets',0),
 ('co-coinbase','coinbase',0),
 ('co-sofi','sofi',0),
 ('co-chime','Chime',1),
 ('co-jane-street','Jane Street',1),
 ('co-jpmorgan-chase','jpmorgan chase',0),
 ('co-jpmorgan-chase','jpmorgan',0),
 ('co-jpmorgan-chase','jp morgan',0),
 ('co-jpmorgan-chase','jpm',0),
 ('co-jpmorgan-chase','jp morgan chase',0),
 ('co-jpmorgan-chase','Chase',1),
 ('co-bank-of-america','bank of america',0),
 ('co-bank-of-america','bofa',0),
 ('co-wells-fargo','wells fargo',0),
 ('co-citigroup','citigroup',0),
 ('co-citigroup','citi',0),
 ('co-citigroup','citibank',0),
 ('co-goldman-sachs','goldman sachs',0),
 ('co-goldman-sachs','goldman',0),
 ('co-morgan-stanley','morgan stanley',0),
 ('co-capital-one','capital one',0),
 ('co-capital-one','capitalone',0),
 ('co-us-bank','U.S. Bank',1),
 ('co-us-bank','us bank',0),
 ('co-us-bank','us bancorp',0),
 ('co-fidelity','fidelity investments',0),
 ('co-fidelity','fidelity',0),
 ('co-vanguard','vanguard',0),
 ('co-blackrock','blackrock',0),
 ('co-blackrock','black rock',0),
 ('co-state-street','State Street',1),
 ('co-citadel','citadel',0),
 ('co-two-sigma','two sigma',0),
 ('co-bridgewater','bridgewater associates',0),
 ('co-bridgewater','bridgewater',0),
 ('co-blackstone','blackstone',0),
 ('co-state-farm','state farm',0),
 ('co-progressive','Progressive',1),
 ('co-progressive','progressive insurance',0),
 ('co-allstate','allstate',0),
 ('co-liberty-mutual','liberty mutual',0),
 ('co-geico','geico',0),
 ('co-metlife','metlife',0),
 ('co-usaa','usaa',0),
 ('co-unitedhealth-group','unitedhealth group',0),
 ('co-unitedhealth-group','unitedhealth',0),
 ('co-unitedhealth-group','united health',0),
 ('co-unitedhealth-group','united healthcare',0),
 ('co-unitedhealth-group','unitedhealthcare',0),
 ('co-unitedhealth-group','uhg',0),
 ('co-unitedhealth-group','optum',0),
 ('co-cvs-health','cvs health',0),
 ('co-cvs-health','cvs',0),
 ('co-cvs-health','aetna',0),
 ('co-elevance-health','elevance health',0),
 ('co-elevance-health','elevance',0),
 ('co-elevance-health','Anthem',1),
 ('co-cigna','the cigna group',0),
 ('co-cigna','cigna',0),
 ('co-humana','humana',0),
 ('co-kaiser-permanente','kaiser permanente',0),
 ('co-kaiser-permanente','kaiser',0),
 ('co-mayo-clinic','mayo clinic',0),
 ('co-cleveland-clinic','cleveland clinic',0),
 ('co-pfizer','pfizer',0),
 ('co-johnson-and-johnson','Johnson & Johnson',1),
 ('co-johnson-and-johnson','johnson and johnson',0),
 ('co-johnson-and-johnson','J&J',1),
 ('co-johnson-and-johnson','jnj',0),
 ('co-merck','merck co',0),
 ('co-merck','merck',0),
 ('co-abbvie','abbvie',0),
 ('co-eli-lilly','eli lilly',0),
 ('co-bristol-myers-squibb','bristol myers squibb',0),
 ('co-bristol-myers-squibb','bms',0),
 ('co-bristol-myers-squibb','bristol myers',0),
 ('co-amgen','amgen',0),
 ('co-gilead','gilead sciences',0),
 ('co-gilead','gilead',0),
 ('co-moderna','moderna',0),
 ('co-genentech','genentech',0),
 ('co-medtronic','medtronic',0),
 ('co-abbott','abbott',0),
 ('co-abbott','abbott laboratories',0),
 ('co-abbott','abbott labs',0),
 ('co-stryker','stryker',0),
 ('co-boston-scientific','boston scientific',0),
 ('co-intuitive-surgical','intuitive surgical',0),
 ('co-ge-healthcare','ge healthcare',0),
 ('co-thermo-fisher','thermo fisher scientific',0),
 ('co-thermo-fisher','thermo fisher',0),
 ('co-illumina','illumina',0),
 ('co-mckinsey','mckinsey company',0),
 ('co-mckinsey','mckinsey',0),
 ('co-bcg','boston consulting group',0),
 ('co-bcg','bcg',0),
 ('co-bcg','boston consulting',0),
 ('co-bain','bain company',0),
 ('co-bain','bain',0),
 ('co-deloitte','deloitte',0),
 ('co-pwc','pwc',0),
 ('co-pwc','pricewaterhousecoopers',0),
 ('co-ey','EY',1),
 ('co-ey','ernst and young',0),
 ('co-ey','ernst young',0),
 ('co-kpmg','kpmg',0),
 ('co-accenture','accenture',0),
 ('co-booz-allen','booz allen hamilton',0),
 ('co-booz-allen','booz allen',0),
 ('co-cognizant','Cognizant',1),
 ('co-infosys','infosys',0),
 ('co-tcs','tata consultancy services',0),
 ('co-tcs','tcs',0),
 ('co-capgemini','capgemini',0),
 ('co-walmart','walmart',0),
 ('co-target','Target',1),
 ('co-target','target corporation',0),
 ('co-costco','costco',0),
 ('co-home-depot','the home depot',0),
 ('co-home-depot','home depot',0),
 ('co-lowes','lowe s',0),
 ('co-lowes','lowes',0),
 ('co-best-buy','Best Buy',1),
 ('co-best-buy','bestbuy',0),
 ('co-kroger','kroger',0),
 ('co-walgreens','walgreens',0),
 ('co-macys','macy s',0),
 ('co-macys','macys',0),
 ('co-tjx','tjx companies',0),
 ('co-tjx','tjx',0),
 ('co-gap','Gap Inc.',1),
 ('co-gap','Gap',1),
 ('co-ikea','ikea',0),
 ('co-trader-joes','trader joe s',0),
 ('co-trader-joes','trader joes',0),
 ('co-whole-foods','whole foods market',0),
 ('co-whole-foods','whole foods',0),
 ('co-heb','H-E-B',1),
 ('co-heb','heb',0),
 ('co-mcdonalds','mcdonald s',0),
 ('co-mcdonalds','mcdonalds',0),
 ('co-starbucks','starbucks',0),
 ('co-chipotle','chipotle mexican grill',0),
 ('co-chipotle','chipotle',0),
 ('co-chick-fil-a','chick fil a',0),
 ('co-chick-fil-a','chickfila',0),
 ('co-procter-and-gamble','procter gamble',0),
 ('co-procter-and-gamble','procter and gamble',0),
 ('co-procter-and-gamble','P&G',1),
 ('co-pepsico','pepsico',0),
 ('co-pepsico','pepsi',0),
 ('co-coca-cola','the coca cola company',0),
 ('co-coca-cola','coca cola',0),
 ('co-coca-cola','Coke',1),
 ('co-unilever','unilever',0),
 ('co-nestle','nestle',0),
 ('co-nike','nike',0),
 ('co-tesla','tesla',0),
 ('co-ford','ford motor company',0),
 ('co-ford','ford',0),
 ('co-ford','ford motor',0),
 ('co-general-motors','general motors',0),
 ('co-general-motors','GM',1),
 ('co-toyota','toyota',0),
 ('co-honda','honda',0),
 ('co-rivian','rivian',0),
 ('co-waymo','waymo',0),
 ('co-boeing','boeing',0),
 ('co-lockheed-martin','lockheed martin',0),
 ('co-lockheed-martin','lockheed',0),
 ('co-northrop-grumman','northrop grumman',0),
 ('co-northrop-grumman','northrop',0),
 ('co-rtx','rtx',0),
 ('co-rtx','raytheon',0),
 ('co-spacex','spacex',0),
 ('co-anduril','anduril industries',0),
 ('co-anduril','anduril',0),
 ('co-ge-aerospace','ge aerospace',0),
 ('co-ge-aerospace','general electric',0),
 ('co-honeywell','honeywell',0),
 ('co-3m','3m',0),
 ('co-caterpillar','caterpillar',0),
 ('co-deere','deere company',0),
 ('co-deere','deere',0),
 ('co-deere','john deere',0),
 ('co-siemens','siemens',0),
 ('co-att','AT&T',1),
 ('co-att','att',0),
 ('co-verizon','verizon',0),
 ('co-t-mobile','T-Mobile',1),
 ('co-t-mobile','tmobile',0),
 ('co-comcast','comcast',0),
 ('co-disney','the walt disney company',0),
 ('co-disney','disney',0),
 ('co-disney','walt disney',0),
 ('co-netflix','netflix',0),
 ('co-warner-bros-discovery','warner bros discovery',0),
 ('co-warner-bros-discovery','warner bros',0),
 ('co-warner-bros-discovery','warner brothers',0),
 ('co-spotify','spotify',0),
 ('co-bloomberg','bloomberg',0),
 ('co-bloomberg','bloomberg lp',0),
 ('co-electronic-arts','electronic arts',0),
 ('co-electronic-arts','EA',1),
 ('co-epic-games','epic games',0),
 ('co-roblox','roblox',0),
 ('co-riot-games','riot games',0),
 ('co-ups','UPS',1),
 ('co-ups','united parcel service',0),
 ('co-fedex','fedex',0),
 ('co-fedex','fed ex',0),
 ('co-dhl','dhl',0),
 ('co-flexport','flexport',0),
 ('co-delta-air-lines','delta air lines',0),
 ('co-delta-air-lines','delta airlines',0),
 ('co-delta-air-lines','Delta',1),
 ('co-united-airlines','united airlines',0),
 ('co-american-airlines','american airlines',0),
 ('co-southwest-airlines','southwest airlines',0),
 ('co-southwest-airlines','Southwest',1),
 ('co-jetblue','jetblue',0),
 ('co-jetblue','jet blue',0),
 ('co-exxonmobil','exxonmobil',0),
 ('co-exxonmobil','exxon',0),
 ('co-exxonmobil','exxon mobil',0),
 ('co-chevron','chevron',0),
 ('co-shell','Shell',1),
 ('co-shell','shell plc',0),
 ('co-bp','BP',1),
 ('co-marriott','marriott international',0),
 ('co-marriott','marriott',0),
 ('co-hilton','hilton',0),
 ('co-hilton','hilton worldwide',0),
 ('co-hyatt','hyatt',0),
 ('co-scale-ai','Scale AI',1),
 ('co-scale-ai','scaleai',0),
 ('co-cohere','Cohere',1),
 ('co-hugging-face','hugging face',0),
 ('co-hugging-face','huggingface',0),
 ('co-perplexity','Perplexity',1),
 ('co-perplexity','perplexity ai',0),
 ('co-xai','xai',0),
 ('co-apple','apple',0),
 ('co-samsung','samsung electronics',0),
 ('co-samsung','samsung',0),
 ('co-sony','sony',0),
 ('co-dell','dell technologies',0),
 ('co-dell','dell',0),
 ('co-hp','HP Inc.',1),
 ('co-hp','HP',1),
 ('co-hpe','hewlett packard enterprise',0),
 ('co-hpe','hpe',0),
 ('co-lenovo','lenovo',0),
 ('co-cisco','cisco',0),
 ('co-cisco','cisco systems',0),
 ('co-arista','arista networks',0),
 ('co-arista','arista',0),
 ('co-intel','Intel',1),
 ('co-intel','intel corporation',0),
 ('co-amd','amd',0),
 ('co-amd','advanced micro devices',0),
 ('co-qualcomm','qualcomm',0),
 ('co-broadcom','broadcom',0),
 ('co-micron','micron technology',0),
 ('co-micron','micron',0),
 ('co-texas-instruments','texas instruments',0),
 ('co-arm','Arm',1),
 ('co-arm','arm holdings',0),
 ('co-asml','asml',0),
 ('co-tsmc','tsmc',0),
 ('co-tsmc','taiwan semiconductor',0),
 ('co-palo-alto-networks','palo alto networks',0),
 ('co-crowdstrike','crowdstrike',0),
 ('co-crowdstrike','crowd strike',0),
 ('co-fortinet','fortinet',0),
 ('co-okta','okta',0),
 ('co-google','google',0),
 ('co-google','alphabet',0),
 ('co-meta','meta',0),
 ('co-meta','facebook',0),
 ('co-meta','meta platforms',0),
 ('co-amazon','amazon',0),
 ('co-amazon','aws',0),
 ('co-amazon','amazon web services',0),
 ('co-microsoft','microsoft',0),
 ('co-microsoft','msft',0);
