#!/usr/bin/env node
/**
 * Build pipeline.
 *
 * Bundles the Evidence Canvas client (React) with esbuild and emits the CSS,
 * then writes both into worker/generated/client-assets.ts so the Worker can
 * serve a single self-contained deployable with no external asset URLs.
 *
 * Design constraint: the deployed Worker must not depend on a third-party CDN,
 * a font host, an analytics script, or any runtime asset fetch.
 */
import { build } from "esbuild";
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync, readFileSync, existsSync, readdirSync, realpathSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { issuerKeyFingerprint } from "../shared/proof.ts";
import { publicSourceFiles } from "./publication.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const GEN = join(ROOT, "worker", "generated");
mkdirSync(GEN, { recursive: true });

// worker/src/release.ts imports this module. On a fresh checkout it does not exist yet, so tsc and the tests need the
// null placeholder; tools/transparency.mjs replaces it with a signed manifest. An existing file is never overwritten.
export const RELEASE_MANIFEST_PLACEHOLDER = "// GENERATED by tools/transparency.mjs - do not edit by hand. null until a release manifest is signed.\nexport const RELEASE_MANIFEST: string | null = null;\n";
const manifestModule = join(GEN, "release-manifest.ts");
if (!existsSync(manifestModule)) writeFileSync(manifestModule, RELEASE_MANIFEST_PLACEHOLDER);

/**
 * The issuer registries a build can pin. A release build (the default, and what `npm run deploy` runs) pins the committed
 * production registry, db/issuer-public-keys.json, written only by `tools/provision-issuer.mjs --remote`. A local build
 * (--local) pins the local registry that tools/prepare-local.mjs provisions for the local stack. Local keys are never in
 * the production registry, and tools/transparency.mjs refuses to sign a build that did not pin exactly the registry it
 * signs, so a client pinned to local keys cannot be released.
 */
export const PIN_REGISTRIES = { production: "db/issuer-public-keys.json", local: ".wrangler/provision/local-issuer-public-keys.json" };

/**
 * The issuer keys this build pins, from a registry written by tools/provision-issuer.mjs. Each fingerprint is recomputed
 * from the key itself, and the build fails if the file's stated fingerprint differs. Expired keys are dropped; keys
 * provisioned ahead of their quarter are kept, so a release pins them before they are used. Without the file the client
 * build pins nothing (null) and keeps its other key checks.
 *  - __SIWT_ISSUER_FINGERPRINTS__: string[] | null, the sorted fingerprints of the live keys (shared/proof.ts
 *    issuerKeyFingerprint). The client refuses to blind against a key whose fingerprint is not listed.
 *  - __SIWT_ISSUER_REGISTRY_DIGEST__: string | null, SHA-256 (base64url) of the JSON array of those sorted fingerprints,
 *    the same form as issuerKeySetDigest and the transparency archives' issuerKeysDigest.
 */
export async function issuerPins(registryPath = join(ROOT, PIN_REGISTRIES.production), now = Date.now()) {
  if (!existsSync(registryPath)) return { fingerprints: null, digest: null };
  const registry = JSON.parse(readFileSync(registryPath, "utf8"));
  if (!Array.isArray(registry)) throw new Error(`${registryPath} is not a JSON array of issuer keys`);
  const fingerprints = [];
  for (const entry of registry) {
    const { fingerprint, ...key } = entry;
    const computed = await issuerKeyFingerprint(key);
    if (fingerprint !== undefined && fingerprint !== computed) throw new Error(`${registryPath}: the stated fingerprint of ${key.id} does not match the key; re-run node tools/provision-issuer.mjs`);
    if (Date.parse(key.expiresAt) > now) fingerprints.push(computed);
  }
  fingerprints.sort();
  return { fingerprints, digest: createHash("sha256").update(JSON.stringify(fingerprints)).digest("base64url") };
}

/**
 * What a build pins and from where, written beside the client as CLIENT_ISSUER_PINS so tools/transparency.mjs can refuse
 * a release whose client does not pin exactly the registry being signed. registry is 'production' or 'local'.
 */
export async function pinsFor(target, now = Date.now()) {
  if (!(target in PIN_REGISTRIES)) throw new Error(`unknown issuer registry ${target}`);
  return { registry: target, path: PIN_REGISTRIES[target], ...(await issuerPins(join(ROOT, PIN_REGISTRIES[target]), now)) };
}

/**
 * Slugs of the fictional sample employers (db/seed.sql rows of kind 'sample'). A release build leaves their Open Graph
 * images out of the Worker bundle (owner decision 1: production holds no fictional data; the worker would answer 404 for
 * them anyway while SAMPLE_EMPLOYERS is not 'on'); a local build (--local) keeps them for the local stack, which shows them.
 */
export function sampleSlugs(sql = readFileSync(join(ROOT, "db", "seed.sql"), "utf8")) {
  const block = /INSERT INTO companies[^;]*?VALUES([\s\S]*?);/.exec(sql)?.[1] ?? "";
  return [...block.matchAll(/\(\s*'[^']*',\s*'([a-z0-9][a-z0-9-]*)',\s*'(?:[^']|'')*',\s*'sample'/g)].map((m) => m[1]);
}
/** The Open Graph image names a build embeds: every image, except the fictional employers' in a release build. */
export function ogNamesFor(names, { local = false, samples = sampleSlugs() } = {}) {
  const hidden = new Set(local ? [] : samples.map((slug) => `c-${slug}`));
  return names.filter((name) => !hidden.has(name));
}

/**
 * The only verifier the built client will contact (__SIWT_VERIFIER_ORIGIN__, read by web/community-keys.ts
 * pinnedVerifier): a page whose /api/config names any other verifier is refused before anything is sent. A release pins
 * the production verifier (issuer.wrangler.jsonc serves it; wrangler.jsonc VERIFIER_ORIGIN must name it); a local build
 * pins the local verifier that tools/dev.mjs serves (tools/prepare-local.mjs writes the same VERIFIER_ORIGIN).
 */
export function verifierOriginFromConfig(text) {
  const config = JSON.parse(text.replace(/^\s*\/\/.*$/mg, ""));
  const domains = (config.routes ?? []).filter(r => r.custom_domain === true).map(r => r.pattern);
  if (domains.length !== 1 || !/^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$/i.test(domains[0])) throw new Error("The verifier config must name exactly one custom domain.");
  return new URL(`https://${domains[0]}`).origin;
}
export const VERIFIER_ORIGINS = { production: verifierOriginFromConfig(readFileSync(join(ROOT, "issuer.wrangler.jsonc"), "utf8")), local: "http://localhost:8790" };
/** A string var of wrangler.jsonc, read as tools/provision-issuer.mjs reads it (the file is JSONC), or undefined. */
export const wranglerVar = (text, name) => new RegExp(`"${name}"\\s*:\\s*"([^"]*)"`).exec(text ?? "")?.[1];
/**
 * Why a release build (not --local) must be refused, or []. registry: the parsed db/issuer-public-keys.json (or null
 * without one); wranglerText: wrangler.jsonc.
 *  - The committed registry lists sandbox ('demo') keys while the main worker hides the fictional employers
 *    (SAMPLE_EMPLOYERS not exactly 'on', as worker/src/flags.ts reads it): the release would pin and sign keys of
 *    employers production must not hold (owner decision 1). Re-provisioning with samples off drops them.
 *  - wrangler.jsonc's VERIFIER_ORIGIN is not the verifier the client pins, so every browser would refuse the site's
 *    verifier and no one could verify.
 */
export function releaseProblems({ registry, wranglerText }) {
  const problems = [];
  const samples = wranglerVar(wranglerText, "SAMPLE_EMPLOYERS");
  const demo = Array.isArray(registry) ? registry.filter((k) => k?.verificationClass === "demo") : [];
  if (demo.length && samples !== "on") {
    const slugs = [...new Set(demo.map((k) => k.companySlug))].sort();
    problems.push(`${PIN_REGISTRIES.production} lists ${demo.length} sandbox ('demo') key(s) of the fictional employers (${slugs.join(", ")}), but wrangler.jsonc sets SAMPLE_EMPLOYERS to ${samples === undefined ? "nothing" : `'${samples}'`}, so the site hides those employers and a release must not pin or sign their keys. Re-provision the production keys with samples off: ISSUER_MASTER_KEY=<the production master key> node tools/provision-issuer.mjs --remote --no-samples (it drops every sandbox key from the registry, its SQL and .issuer-secrets.json), commit ${PIN_REGISTRIES.production}, then run node tools/build.mjs again. The verifier's own sandbox key rows are deleted by node tools/purge-samples.mjs --remote (a dry run; then --apply --bookmark=<id>). For the local stack, build with node tools/build.mjs --local instead.`);
  }
  const origin = wranglerVar(wranglerText, "VERIFIER_ORIGIN");
  if (origin !== VERIFIER_ORIGINS.production) problems.push(`wrangler.jsonc sets VERIFIER_ORIGIN to ${origin === undefined ? "nothing" : `'${origin}'`}, but a release client pins ${VERIFIER_ORIGINS.production} and refuses any other verifier, so no one could verify. Set VERIFIER_ORIGIN to ${VERIFIER_ORIGINS.production}.`);
  return problems;
}

/** Builds the client and writes worker/generated/{client-assets,og-assets}.ts. Importing this module (tests) builds nothing. */
async function main() {
  const local = process.argv.includes("--local");
  if (!local) {
    const registryPath = join(ROOT, PIN_REGISTRIES.production);
    const problems = releaseProblems({ registry: existsSync(registryPath) ? JSON.parse(readFileSync(registryPath, "utf8")) : null, wranglerText: readFileSync(join(ROOT, "wrangler.jsonc"), "utf8") });
    if (problems.length) {
      console.error(`Refusing a release build: the client was not built and worker/generated was not changed.\n${problems.map((p) => `  - ${p}`).join("\n")}`);
      process.exit(1);
    }
  }
  const pins = await pinsFor(local ? "local" : "production");
  const verifierOrigin = VERIFIER_ORIGINS[local ? "local" : "production"];
  // A release build on a machine with a local stack: say plainly that the local stack's keys are not pinned.
  const localPins = !local && existsSync(join(ROOT, PIN_REGISTRIES.local)) ? await issuerPins(join(ROOT, PIN_REGISTRIES.local)) : null;
  const unpinnedLocal = localPins?.fingerprints?.filter((f) => !pins.fingerprints?.includes(f)) ?? [];

  // zod re-exports ~70 message locales through `z.locales`; the client only uses English messages (the default zod
  // registers itself), so the locale index resolves to English alone. This removes about 250 KB from every page load.
  const zodEnglishOnly = {
    name: "zod-english-only",
    setup(b) {
      b.onResolve({ filter: /^\.\.\/locales\/index\.js$/ }, (args) => args.importer.includes(`${join("node_modules", "zod")}`) ? { path: join(ROOT, "node_modules/zod/v4/locales/en.js"), namespace: "zod-locales" } : undefined);
      b.onLoad({ filter: /.*/, namespace: "zod-locales" }, (args) => ({ contents: `export { default as en } from ${JSON.stringify(args.path)};`, loader: "js", resolveDir: ROOT }));
    },
  };

  const result = await build({
    entryPoints: [join(ROOT, "web", "main.tsx")],
    plugins: [zodEnglishOnly],
    bundle: true,
    minify: true,
    format: "iife",
    target: "es2022",
    jsx: "automatic",
    loader: { ".tsx": "tsx", ".ts": "ts" },
    define: { "process.env.NODE_ENV": '"production"', __SIWT_ISSUER_FINGERPRINTS__: JSON.stringify(pins.fingerprints), __SIWT_ISSUER_REGISTRY_DIGEST__: JSON.stringify(pins.digest), __SIWT_VERIFIER_ORIGIN__: JSON.stringify(verifierOrigin) },
    legalComments: "none",
    write: false,
    logLevel: "warning",
  });

  const js = result.outputFiles[0]?.text ?? "";
  if (!js) throw new Error("client bundle produced no js output");

  // styles.css first, then every other web stylesheet except the font faces, in name order.
  const cssFiles = ["styles.css", ...readdirSync(join(ROOT, "web")).filter((f) => f.endsWith(".css") && f !== "styles.css" && f !== "fonts.css").sort()];
  const css = cssFiles.filter((f) => existsSync(join(ROOT, "web", f))).map((f) => readFileSync(join(ROOT, "web", f), "utf8")).join("\n");

  const fontsPath = join(ROOT, "web", "fonts.css");
  const fonts = existsSync(fontsPath) ? readFileSync(fontsPath, "utf8") : "";

  // Exact, reviewed paths only. A new local file is never picked up by a directory crawl.
  const sourceFiles = publicSourceFiles(ROOT);
  const out = `// GENERATED by tools/build.mjs - do not edit by hand.
export const CLIENT_JS = ${JSON.stringify(js)};
export const CLIENT_CSS = ${JSON.stringify(css)};
export const CLIENT_FONTS = ${JSON.stringify(fonts)};
export const CLIENT_BUILD_ID = ${JSON.stringify(createHash("sha1").update(js + css + fonts).digest("hex").slice(0, 10))};
export const BUILD_BYTES = ${js.length + css.length + fonts.length};
export const SOURCE_FILES = ${JSON.stringify(sourceFiles)};
export const CLIENT_ISSUER_PINS = ${JSON.stringify(pins)};
`;
  writeFileSync(join(GEN, "client-assets.ts"), out);

  // Open Graph images: pre-rendered by tools/og.mjs into web/og/<name>.jpg (1200x630, at most 90 KB each) and served by
  // worker/src/og.ts. Only files that pass the name and size checks are embedded.
  // A release build leaves the fictional employers' images out (sampleSlugs); a local build keeps them.
  const OG_DIR = join(ROOT, "web", "og"), OG_LIMIT = 90 * 1024;
  const og = {}, embedded = new Set(ogNamesFor(existsSync(OG_DIR) ? readdirSync(OG_DIR).map((f) => /^([a-z0-9][a-z0-9-]{0,99})\.jpg$/.exec(f)?.[1]).filter(Boolean) : [], { local }));
  if (existsSync(OG_DIR)) for (const file of readdirSync(OG_DIR).sort()) {
    const name = /^([a-z0-9][a-z0-9-]{0,99})\.jpg$/.exec(file)?.[1];
    if (!name || !embedded.has(name)) continue;
    const bytes = readFileSync(join(OG_DIR, file));
    if (bytes.length > OG_LIMIT) throw new Error(`web/og/${file} is ${bytes.length} bytes; the limit is ${OG_LIMIT}. Re-run node tools/og.mjs.`);
    if (bytes[0] !== 0xff || bytes[1] !== 0xd8) throw new Error(`web/og/${file} is not a JPEG`);
    og[name] = bytes.toString("base64");
  }
  writeFileSync(join(GEN, "og-assets.ts"), `// GENERATED by tools/build.mjs from web/og/*.jpg - do not edit by hand.\nexport const OG_IMAGES:Record<string,string>=${JSON.stringify(og)};\n`);

  console.log(
    `build ok  js=${(js.length / 1024).toFixed(1)}kb  css=${(css.length / 1024).toFixed(1)}kb  fonts=${(fonts.length / 1024).toFixed(1)}kb  og=${Object.keys(og).length} images${local ? "" : " (fictional employers' left out)"}  verifier pinned=${verifierOrigin}  issuer keys pinned=${pins.fingerprints ? `${pins.fingerprints.length} from the ${pins.registry} registry ${pins.path} (${pins.digest})` : `none (no ${pins.path}${local ? "; run node tools/prepare-local.mjs" : ""})`}`,
  );
  if (unpinnedLocal.length) console.warn(`note: this is a release build pinned to the production registry; the local stack's ${unpinnedLocal.length} keys (${PIN_REGISTRIES.local}) are not pinned, so the local contribution and juror flows will refuse them. For the local stack, build with node tools/build.mjs --local (never release that build).`);
}
const isMain = () => !!process.argv[1] && realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url));
if (isMain()) await main();
