// Local only. Writes one env file per worker so each local worker sees only its own secrets, migrates the three local
// D1 databases, seeds the local public database only when it is empty, then provisions and loads locally sealed issuer
// keys (after migrating, so the keys get the headcount-band limits and the purpose column exists). Local keys live under
// .wrangler/provision/ (tools/provision-issuer.mjs provisionFiles), never in .issuer-secrets.json or the committed
// db/issuer-public-keys.*, and the client is built pinned to them (node tools/build.mjs --local).
import {existsSync,readFileSync,writeFileSync,mkdirSync,realpathSync,statSync,chmodSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {randomBytes} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {provisionFiles} from './provision-issuer.mjs';

const random=()=>randomBytes(32).toString('base64url');
/**
 * Pure: the env file for each local worker. Local secrets are kept across runs (locally sealed issuer keys must stay
 * readable) and are local values only, never production secrets. The inference worker defaults to the TypeSafe HTTP API
 * locally, because inference.wrangler.jsonc selects the remote, billable Workers AI binding. The local main worker shows
 * the fictional sample employers (SAMPLE_EMPLOYERS=on; production sets 'off' in wrangler.jsonc), and so does the local
 * verifier, which lists and signs with their sandbox keys only while its own SAMPLE_EMPLOYERS is exactly 'on'
 * (production sets 'off' in issuer.wrangler.jsonc): without it, local practice juries and the browser and integration
 * suites lose the sandbox keys. INTERNAL_TOKEN is the
 * one secret the main worker and the verifier share (the verifier's internal registration route over the VERIFIER
 * service binding): the same local value goes into both files, kept across runs, and it is never a production value.
 */
export function localVars(existing,environment,generate=random) {
 const verifier=existing.verifier??{},main=existing.main??{},inference=existing.inference??{};
 const publicVars={ENVIRONMENT:'development',VERIFIER_ORIGIN:'http://localhost:8790'};
 const internal=main.INTERNAL_TOKEN||verifier.INTERNAL_TOKEN||generate();
 return {
  '.dev.vars.main':{...publicVars,SAMPLE_EMPLOYERS:'on',RATE_LIMIT_SECRET:main.RATE_LIMIT_SECRET||generate(),INTERNAL_TOKEN:internal},
  // A key set in .env or the shell wins; otherwise the key already in the file is kept rather than blanked.
  '.dev.vars.inference':{ENVIRONMENT:'development',JEV_PROVIDER:'typesafe',TYPESAFE_API_KEY:environment.TYPESAFE_API_KEY||inference.TYPESAFE_API_KEY||''},
  '.dev.vars.verifier':{ENVIRONMENT:'development',SAMPLE_EMPLOYERS:'on',MAILBOX_PEPPER:verifier.MAILBOX_PEPPER||generate(),ISSUER_MASTER_KEY:verifier.ISSUER_MASTER_KEY||generate(),INTERNAL_TOKEN:internal},
  // The legacy shared file gave every local worker every secret. It stays as a secrets-free copy of the main worker's
  // public vars: without any .dev.vars, a plain `wrangler dev` would load .env (provider key, admin token) into any worker.
  '.dev.vars':publicVars,
 };
}
/** Secrets exported in the shell or loaded from .env never reach child processes that do not own them. */
export const withoutSecrets=environment=>Object.fromEntries(Object.entries(environment).filter(([key])=>!/TYPESAFE|ISSUER|MAILBOX_PEPPER|ADMIN_TOKEN|MASTER_KEY|RATE_LIMIT_SECRET|INTERNAL_TOKEN/.test(key)));
/**
 * Writes only the per-worker env files (--env-only): no migration, provisioning or build. For a running local stack after
 * a new local var or shared secret; restart the workers whose file changed (node tools/dev.mjs --restart --only=...).
 */
export const ENV_ONLY_FLAG='--env-only';
/**
 * .env holds the provider key and the admin token for local tools, so it must be readable by its owner only. True when
 * it holds a secret and group or others can read it (prepare-local then sets 0600). Pure: mode is the file's st_mode.
 */
export function envFileNeedsTightening(mode,text) {return (mode&0o077)!==0&&/^\s*(?:export\s+)?[A-Z0-9_]*(?:KEY|TOKEN|SECRET|PEPPER|PASSWORD)[A-Z0-9_]*\s*=\s*\S/m.test(text);}
const PLACEHOLDER='// GENERATED by tools/transparency.mjs - do not edit by hand. null until a release manifest is signed.\nexport const RELEASE_MANIFEST: string | null = null;\n';

function main() {
 if(existsSync('.env')) {
  if(envFileNeedsTightening(statSync('.env').mode,readFileSync('.env','utf8'))) {chmodSync('.env',0o600);console.log('.env holds secrets and was readable by other users, so its mode was set to 0600.');}
  process.loadEnvFile('.env');
 }
 const read=file=>existsSync(file)?Object.fromEntries(readFileSync(file,'utf8').split('\n').filter(line=>/^[A-Z_]+=/.test(line)).map(line=>[line.slice(0,line.indexOf('=')),line.slice(line.indexOf('=')+1).trim()])):{};
 const write=(file,vars)=>writeFileSync(file,`${Object.entries(vars).map(([key,value])=>`${key}=${value}`).join('\n')}\n`,{mode:0o600});
 const files=localVars({main:read('.dev.vars.main'),verifier:read('.dev.vars.verifier'),inference:read('.dev.vars.inference')},process.env);
 for(const [file,vars] of Object.entries(files))write(file,vars);
 if(process.argv.includes(ENV_ONLY_FLAG)){console.log('Local env files rewritten (.dev.vars, .dev.vars.main, .dev.vars.inference, .dev.vars.verifier); secrets were kept and not printed. Restart the workers whose file changed: node tools/dev.mjs --restart --only=main,verifier.');return;}
 // worker/src/release.ts imports this module; until a release is signed it serves 404 no_release_manifest.
 if(!existsSync('worker/generated/release-manifest.ts')){mkdirSync('worker/generated',{recursive:true});writeFileSync('worker/generated/release-manifest.ts',PLACEHOLDER);}
 const run=(command,args,extra={})=>{const r=spawnSync(command,args,{stdio:'inherit',env:{...withoutSecrets(process.env),...extra}});if(r.status)process.exit(r.status);};
 run('node',['tools/db.mjs','local','--seed-if-empty']);
 const keys=provisionFiles(false);
 run('node',['tools/provision-issuer.mjs'],{ISSUER_MASTER_KEY:files['.dev.vars.verifier'].ISSUER_MASTER_KEY});
 run('bunx',['wrangler','d1','execute','shouldiworkthere-public','--local','--config','wrangler.jsonc','--file',keys.publicSql,'--yes']);
 run('bunx',['wrangler','d1','execute','shouldiworkthere-verifier','--local','--config','issuer.wrangler.jsonc','--file',keys.sealed,'--yes']);
 // The local client pins the local keys; a release build (without --local) pins the production registry instead.
 run('node',['tools/build.mjs','--local']);
 console.log(`Local bindings prepared: .dev.vars (no secrets), .dev.vars.main (SAMPLE_EMPLOYERS=on, a local RATE_LIMIT_SECRET and the local INTERNAL_TOKEN), .dev.vars.inference (JEV_PROVIDER=typesafe and the provider key${files['.dev.vars.inference'].TYPESAFE_API_KEY?'':', which is empty: set TYPESAFE_API_KEY in .env for hosted Jev locally'}), .dev.vars.verifier (SAMPLE_EMPLOYERS=on, verifier secrets and the same local INTERNAL_TOKEN). Local issuer keys: ${keys.registry}, pinned by the local client build. Secrets were not printed. Start with node tools/dev.mjs; after web/ changes rebuild with node tools/build.mjs --local.`);
}
if(process.argv[1]&&realpathSync(process.argv[1])===realpathSync(fileURLToPath(import.meta.url))) main();
